replicaCount: 1

image:
  repository: node
  tag: 18-alpine

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: ""  # Leave this empty to auto-generate a name from chart fullname

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

