apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
    spec:
      containers:
        containers:
      - name: game-2048
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
