apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ include "helm-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
