{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "helm-chart.fullname" .) }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
{{- end }}
